### ISSUE TITLE
Too many spawns

### ISSUE THREAD

**Issue by JojoMeowstic** [DakotaPride/More-Weaponry-1.18#10]
I have endlessly spawning overly powerful buried knights and many dungeons spawned with them everywhere, but I cannot change the settings of the mod to cut down the spawns

**Comment by DakotaPride** [comment]
> I have endlessly spawning overly powerful buried knights and many dungeons spawned with them everywhere, but I cannot change the settings of the mod to cut down the spawns

I apologize for the unfortunate spawn rates of the mobs, this will be fixed soon (later today in v2.2.5), making them spawn much less frequently. Thank you for your patience!

**Comment by DakotaPride** [comment]
While curseforge hasn't yet approved the file, I have now updated the mod on [Modrinth](https://modrinth.com/mod/more-weaponry/version/v2.2.5%2B1.19.2)!

**Comment by Dekonker** [comment]
I'm using v2.2.5+1.19.2 and this appears to be still happening. It is crashing my server because it's spawning an insane amount of buried knights.

**Comment by DakotaPride** [comment]
Is this also an issue with the Crawler mob? As, at this point in time, I'm now removing natural spawns and making it a fixed number of spawns (similar to woodland mansions)

**Comment by DakotaPride** [comment]
I've updated More Weaponry, as before, it is not yet approved on Curseforge (though it will most likely be updated by Monday). It is uploaded to Modrinth however. Let me know if there's anything else!

[More Weaponry Modrinth v2.3](https://modrinth.com/mod/more-weaponry/version/v2.3)
