### ISSUE TITLE
[SUGGESTION THREAD] What do you want to be in the mod's next big update?

### ISSUE THREAD

**Issue by DakotaPride** [DakotaPride/More-Weaponry-1.18#5]
The next version will be posted after 1.19 comes out! With such a long time gap between v1.18 Alpha and v1.18.8, what happens next?
This is where the community (you) comes in! Leave your suggestions below this thread to have a chance of having them included in the next update!

If you do have a suggestion that makes it in, you will be credited for it as well as be marked 'contributor'.
![](https://user-images.githubusercontent.com/82760983/161865915-e62440a4-09bf-4578-a531-bce85818410c.png)

**Comment by LordDennis18** [comment]
An underground fortress a rare huge structure  found on large caves filled with strong enemies and epic tier loot. Maybe introduce new enemies? Exclusive only to this underground fortress.
Enemies:
Crawler- a rare type of guard that is equipped with iron or chainmail armor. That crawls underground and dig up to attack you. It can detect you from 16 blocks away. It has 25 health and deals decent damage depending on what weapons it uses. 
Loot drops:
A new type of weapon called Bothering Might. This weapon has a chance to confuse enemies. This weapon can deal 7 dmg.
Set of iron armor
Set of chainmail armor
iron ingot 1-3

Buried Knight- A strong and deadly guard that is equipped with any armor in the mod (depends what fits in). This has over 50 health and has a chance to have enchanted weapons either vanilla or modded. It can also weaken the player by 3 seconds.
Loot drops:
A new type of weapon called Heavy Sword. A rare drop from the buried knight that deals 9 heavy damage and requires two-handed to use it. A new effect called bleeds that is already on the Heavy Sword. Can be an enchantment from I-III the higher the enchantment the more you bleed in a second. 
Iron Ingot 2-4
A set of armor in the mod that fits in with the mob.

Buried Crossbowman- A lightly armored guard that can fire a new type of crossbow called Heavy Crossbow. Fully made with iron and uses a new type of ammunition called Iron Bolt that pierces into 2 enemies. This enemy can be equipped with leather and gold armor or maybe a new type of armor that is exclusive with the crossbowman that also has a set bonus of increasing the dmg of crossbow and bows.
Loot Drops:
Heavy Crossbow
A new set type of armor
Gold ingot 1-2
Iron Bolt 2-5

Necromancer- A strong magic enemy that spawns 3 skeletons and has a chance to spawn armored wither skeletons. Once a necromancer spawned 3 enemies it has a cooldown of 10 seconds before it can spawn another 3 more. While the summoning is on cooldown the necromancer can fire magic that deals decent dmg on the player.
Loot Drops:
A new type of weapon called the staff of Xen that summons 1 flying ghoul that is equipped with bow. This weapon has a chance to spawn a ghoul with an enchanted bow. cannot be modified it stats.
Ender pearl 1-2
Bottle of Poison 1
Spider eye 1-2

Boss:
My final suggestion would be a new type of boss that can be summoned somewhere in the fortress where you can fought it 1on1.
Tatum Underhille, The guardian of the hidden fortress- This boss has over 650 health and has a big sword that deals 12 dmg on the players. This boss can stomp the ground and slow the player. It can also spawn random enemies maximum of 5 enemies. The boss can also darken your screen once the boss is down with half health. It can charge the player to deal a massive damage using it's big sword making you instantly bleed. Once the boss is beaten it can drop a new material called Blessed Titanium a new type of metal bar and one of the strongest material in the mod. This can craft a new set of armor and a set of weapons and tools. Also a new exclusive weapon called Striking Madness a weapon that the boss uses in the battle. It has a chance to deal bleeding III on any enemies. It deals over 15 dmg on enemies and can give the player a strength II making it a one-handed heavy sword but gives a slowness I debuff.


Overall Suggestion
Structures
-Underground Fortress
Enemies
-Crawler
-Buried Knight
-Buried Crossbowman
-Necromancer
-Tatum Underhille, The guardian of the hidden fortress
Weapons and Armors
-Bothering Might
-Heavy Crossbow
-Staff of Xen
-Striking Madness
-Blessed Titanium weapons, tools and armor set
Enchantment
-Bleeding I-III
Items
-Iron Bolt
-Blessed Titanium

This are the things I can suggest from this mod. It has a lot of potential so here I am giving some well thought out ideas that can be applied in the 1.19 major update. If you want me to add more details with each included suggestions just let me know:)

**Comment by DakotaPride** [comment]
I know it's been a bit over a week, but I am working on getting these features in as well as a few other fixes/adjustments to older features. Starting Work On The Actual Structure Itself, as well as finishing up items. With some of the newer 1.19 snapshots coming out, introducing stuff like the Echo Shards, I think I can implement those into the above concepts if that's fine with you (of course, the implementation of 1.19 items/blocks would be later on, as it's still in snapshots and not finalized)

**Comment by LordDennis18** [comment]
Of course! that's all fine with me. Glad to suggest a few things that comes up in my mind. Goodluck with the upcoming major update in 1.19!

**Comment by ghost** [comment]
The mod is really cool, but I believe it needs a texture/model update in order to fit more with Vanilla and other mods.

**Comment by DakotaPride** [comment]
> 

I have been planning on majorly updating the textures for a while, but wasn't quite sure exactly where to start. I already have some texture reworks in mind (such as frodon wood, material blocks such as blackstone metal, mare diamond, and cirtict, among others). If you could please provide some textures that you personally want to be changed, feel free to let me know and I'll look into it!

**Comment by ghost** [comment]
Hello! Sorry for not getting back to you earlier. Most textures shape and design actually look quite great, the only issue is that the color combination doesn't quite match with Minecraft's style. This applies to most tools and a lot of the materials. Minecraft's item textures tend to have dark, contrasting outlines. Another item that needs a revamp is the reinforced crossbow, because Minecraft doesn't really do polygonal models of that style for held items, or even entity items for that case.

I might even be willing to perhaps collaborate with this mods texturing, if it's alright with you. I've done textures for mods and resource packs for quite a while now, and I would really like to see this mod gain more traction as its mechanics are quite complex in comparison to a lot of other weapon mods.

**Comment by DakotaPride** [comment]
> 

I'll go ahead and see if I can match it a bit better, I'm not the best at art, let alone pixel art. I've also kind of been trying to decide whether or not I want to go with the Minecraft style more or less, as it is a mod and isn't meant to feel vanilla (at least in this case). With that being said, there are a few things that I will not change in terms of design, such as the Heavy Crossbow, which I wanted to be like that due to another 'heavy' weapon also being a 3d model (Heavy Sword).

With all of that being said, If you would like to create some textures for the mod you can, but I cannot guarantee that they're used, as I'm still learning this whole modding thing and wanted it to be a mainly solo project (including texturing, concepts, functionality, etc.) with minor help from people. Again, if you do decide to make some textures for the mod, I'll what I can do to get them in, but again, not a guarantee. Thank you for your understanding!

Let me know if there's anything else that I should/could add/change!
