### ISSUE TITLE
Modrinth's page for this mod says that it is a, **"Universal mod"**.

### ISSUE THREAD

**Issue by ghost** [DakotaPride/More-Weaponry-1.18#8]
On More Weaponry's Modrinth page, I saw that More Weaponry was **"Universal mod"**.

![image](https://user-images.githubusercontent.com/65317484/179817065-eeb71cb1-e929-4319-a30f-feff9e247222.png)
This does not make any sense because at, https://github.com/HoloScopeStudios/More-Weaponry#about the page says, **"More Weaponry implements new tools and bosses for your journey!"**.

Pictures of the mod that are shown here, **https://modrinth.com/mod/more-weaponry/gallery** looks like this mod is required on the server & client.
![image](https://user-images.githubusercontent.com/65317484/179818332-97118d8f-993b-4049-9996-b04735eb1b1b.png)

# Technical information about the mod, says that is it, **"Optional"**.
![image](https://user-images.githubusercontent.com/65317484/179816795-7e029b82-a834-4a0c-a9ab-41425739b463.png)
**To me, this means,** the mod isn't required on either the server or client.

From what I can tell, Only More Weaponry's page on Modrinth, Says that the mod is **"Universal mod"**, and is **"Optional"** on the client & server.
# **Please fix so that others don't mistake this as a "Server-side mod"!**

**Comment by DakotaPride** [comment]
I apologize for the misunderstanding (I thought that it had meant what environments the mod works in). I have now changed it to be required on both the client and the server. Again, apologies for this issue. If you have any other concerns about the mod page/issues that you come by, please let me know!
